import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from touched_files import collect_touched_files, write_touched_files


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)


class TouchedFilesTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = Path(tempfile.mkdtemp(prefix="sxlb-touched-files-"))
        git(self.temp_dir, "init")
        git(self.temp_dir, "config", "user.email", "sxlb@example.test")
        git(self.temp_dir, "config", "user.name", "SXLB Test")
        write(self.temp_dir / "README.md", "initial\n")
        git(self.temp_dir, "add", "README.md")
        git(self.temp_dir, "commit", "-m", "initial")

    def tearDown(self) -> None:
        shutil.rmtree(self.temp_dir)

    def test_collect_touched_files_includes_modified_staged_and_untracked_paths(self) -> None:
        write(self.temp_dir / "README.md", "changed\n")
        write(self.temp_dir / "staged.txt", "staged\n")
        git(self.temp_dir, "add", "staged.txt")
        write(self.temp_dir / "untracked.txt", "untracked\n")

        touched = collect_touched_files(self.temp_dir)

        self.assertEqual(touched, ["README.md", "staged.txt", "untracked.txt"])

    def test_write_touched_files_creates_guard_consumable_list(self) -> None:
        write(self.temp_dir / "scripts" / "tool.py", "print('changed')\n")
        output = self.temp_dir / "subagents" / "returns" / "touched-files-office-01.txt"

        write_touched_files(self.temp_dir, output)

        text = output.read_text(encoding="utf-8")
        self.assertIn("# generated by sxlb touched-files helper", text)
        self.assertIn("scripts/tool.py\n", text)


if __name__ == "__main__":
    unittest.main()
