#!/usr/bin/env python3
"""Generate an independent touched-files list for sxlb real-subagent returns."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def run_git(repo: Path, *args: str) -> list[str]:
    result = subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def collect_touched_files(repo: Path) -> list[str]:
    """Return changed git paths relative to repo, including staged and untracked files."""
    repo = repo.resolve()
    paths: set[str] = set()
    paths.update(run_git(repo, "diff", "--name-only"))
    paths.update(run_git(repo, "diff", "--cached", "--name-only"))
    paths.update(run_git(repo, "ls-files", "--others", "--exclude-standard"))
    return sorted(paths)


def render_touched_files(paths: list[str]) -> str:
    lines = ["# generated by sxlb touched-files helper", ""]
    lines.extend(paths)
    return "\n".join(lines).rstrip() + "\n"


def write_touched_files(repo: Path, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_touched_files(collect_touched_files(repo)), encoding="utf-8")
    return output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an sxlb touched-files evidence list.")
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Git repository root or working tree")
    parser.add_argument("--output", type=Path, required=True, help="Output touched-files list path")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    print(write_touched_files(args.repo, args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
